SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 497, 'shrink': 879, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 482, 'shrink': 634, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 880, 'shrink': 96, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 173, 'shrink': 887, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 376, 'shrink': 448, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 5 Exception. Config: {'topK': 5, 'shrink': 896, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 6 Exception. Config: {'topK': 373, 'shrink': 598, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 7 Exception. Config: {'topK': 833, 'shrink': 277, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 8 Exception. Config: {'topK': 17, 'shrink': 405, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 9 Exception. Config: {'topK': 618, 'shrink': 246, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 10 Exception. Config: {'topK': 531, 'shrink': 781, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 11 Exception. Config: {'topK': 293, 'shrink': 991, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 12 Exception. Config: {'topK': 428, 'shrink': 458, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 13 Exception. Config: {'topK': 210, 'shrink': 554, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Config 14 Exception. Config: {'topK': 112, 'shrink': 755, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\HyperparameterTuning\SearchAbstractClass.py", line 294, in _fit_model
    recommender_instance = self.recommender_class(*self.recommender_input_args.CONSTRUCTOR_POSITIONAL_ARGS,
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\KNN\ItemKNNCBFRecommender.py", line 26, in __init__
    super(ItemKNNCBFRecommender, self).__init__(URM_train, ICM_train, verbose = verbose)
  File "C:\Users\Luca\DataspellProjects\Recommender-Systems-Challenge-2022\Recommenders\BaseCBFRecommender.py", line 24, in __init__
    assert self.n_items == ICM_train.shape[0], "{}: URM_train has {} items but ICM_train has {}".format(self.RECOMMENDER_NAME, self.n_items, ICM_train.shape[0])
AssertionError: ItemKNN_CFCBF_HybridRecommender: URM_train has 24507 items but ICM_train has 27968

SearchBayesianSkopt: Search interrupted. No valid config was found during the initial random initialization
